Project File/online_recharge_system/Models/SupportEmail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace online_recharge_system.Models
{
    public class SupportEmail 
    {
        // [Display(Name = "Email")]
        // [Required(ErrorMessage = "Please enter the email")]
        // [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$"
        //     , ErrorMessage = "Not a Valid Mail")]
        // [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        public string to { get; set; }

        public string subject { get; set; }

        public string body { get; set; }

    }
}

Project File/online_recharge_system/Controllers/SupportEmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using online_recharge_system.Models;

namespace online_recharge_system.Controllers
{
    public class SupportEmailController : Controller
    {
        // GET: SupportEmail
        public ActionResult Supportlog()
        {
            if (Session["UserID"] != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Supportlog(SupportEmail ec)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("http://192.168.2.156:80/api/SupportEmailAPI/Supportlog");

            var consumeapi = hc.PostAsJsonAsync<SupportEmail>("Email", ec);
            consumeapi.Wait();

            var sendmail = consumeapi.Result;
            if (sendmail.IsSuccessStatusCode)
            {
                ViewBag.support = "THE MAIL SUCCESSFULLY SENT";
            }
            return View();
        }
    }
}

Project File/online_recharge_system/Views/SupportEmail/Supportlog.cshtml
@model online_recharge_system.Models.SupportEmail
@{
    ViewBag.Title = "Supportlog";
    Layout = "~/Views/Shared/_AUTHLayout.cshtml";
}
<section style="background: linear-gradient(to left, #2193b0, #6dd5ed); ">
    <div class="swiper-container col-md-5 col-lg-7 col-sm-7">
        <br />
        <br />
        @using (Html.BeginForm("Supportlog", "SupportEmail", FormMethod.Post, new { enctype = "multiport/form-data" }))
        {
            <center>
                <div class="card container col-md-5 col-lg-7 col-sm-7">
                    <div class="card-footer bg-warning">
                        <h4 class="text-white">SUPPORT</h4>
                    </div>
                    <div class="card-body" style="background-color: #ffbd77;background-image: linear-gradient(319deg, #ffbd77 0%, #f0f4a4 37%, #acfcd9 100%);">
                        <div class="form-group">
                            <div class="form-group">
                                <div class="col">
                                    <label>Your Email</label>
                                </div>
                                <div class="col">
                                    @Html.TextBoxFor(model => model.to, new { @class = "form-control" })
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col">
                                    <label>Your Name</label>
                                </div>
                                <div class="col">
                                    @Html.TextBoxFor(model => model.subject, new { @class = "form-control" })
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col">
                                    <label>Support</label>
                                </div>
                                <div class="col">
                                    @Html.TextAreaFor(model => model.body, new { @class = "form-control" })
                                </div>
                            </div>
                            <input id="Button1" class="btn btn-block btn-danger" type="submit" value="sendmail" />
                        </div>
                    </div>
                    <h5 class="bg-warning">@ViewBag.support</h5>
                </div>
            </center>
        }
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
</section>